version: '3'
services:
    apache:
        image: "eboraas/apache-php"
        ports:
            - '8080:80'
            - '443:443'
        volumes:
            - ./app/:/var/www/html/
    mysql:
        image: "mysql:8.0.1"
        environment:
            MYSQL_ROOT_PASSWORD: "qwqwqwopl3"
            MYSQL_DATABASE: "devopsteam3"
        ports: 
            - 3306:3306
